config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'sessions#new'
  
  # Define the route to make it more friendly
  # get 'signup', to: 'users#new', as: 'signup'
  # get 'login', to: 'sessions#new', as: 'login'
  # get 'logout', to: 'sessions#destroy', as: 'logout'
  # get '/vote', to: 'votes#create', as: 'vote'


	get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # resources :users
  # resources :sessions, only: [:create]
  resources :recipes
  resources :vote, only: [:create]
  root 'welcome#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :user
	
	validates_presence_of :title, :ingredients, :steps

	serialize :photos, Array
	mount_uploaders :photos, PhotoUploader

	# has_many :recipes, dependent: :destroy

	paginates_per 5

	def self.search(search)
    result = []
    result << where("title ILIKE ?", "%#{search}%")
    result << where("description ILIKE ?", "%#{search}%") 
    result << where("ingredients ILIKE ?", "%#{search}%")
    
    i = 0
    while i < 3
      return result[i] if result[i].length > 0 
      i += 1
    end
  end
end


# => ["id", "user_id", "title", "description", "ingredients", "steps", "photos", "created_at", "updated_at"]

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :set_recipe, only: [:show, :edit, :update, :destroy]


	def index
		# @recipes = Recipe.all
		if params[:search]
      @recipes = Recipe.search(params[:search])
      if @recipes.nil?
        flash[:notice] = "There are no posts containing the terms \"#{params[:search]}\""
        redirect_to recipes_path
      else
       @recipes = @recipes.order("created_at DESC").page params[:page]
     end
    else
      @recipes = Recipe.order(:title).page params[:page]
    end
	end

	def create
		@recipe = current_user.recipes.new(recipe_params)
		if @recipe.save
			redirect_to recipes_path, notice: "Recipe has succesfully created"
		else
			render :new
		end
	end

	def new
		@recipe = Recipe.new
	end

	def show
  end

	def edit
	end

	def update
		# Cloudinary::Uploader.upload(params[image, auth)
		if @recipe.update(recipe_params)
			redirect_to @recipe, notice: 'Recipe was succesfully updated'
		else
			render :edit
		end
	end

	def vote
	end

	private
	def set_recipe
		@recipe = Recipe.find(params[:id])
	end

	def recipe_params
		params.require(:recipe).permit(:title, :description, :ingredients, :steps, photos: [])
	end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div class="pt-2 pl-4 pr-4">
<div class="field">
	<%= form.label :title %> <br>
	<%= form.text_field :title, class:"form-control" %>
</div>
<br>
<div class="field">
	<%= form.label :description %> <br>
	<%= form.text_area :description, class:"form-control", rows:"3" %>
</div>
<br>
<div class="field">
	<%= form.label :ingredients %> <br>
	<%= form.text_area :ingredients, class:"form-control", rows:"4" %>
</div>
<br>
<div class="field">
	<%= form.label :steps %> <br>
	<%= form.text_area :steps, class:"form-control", rows:"4" %>
</div>
<br>
<div class="field">
	<%= form.label :photos %> <br>
	<%= form.file_field :photos, multiple: true %>
</div>
</div>
<!--  => ["id", "user_id", "title", "description", "ingredients", "steps", "photos", "created_at", "updated_at"]
 -->

app/views/recipes/edit.html.erb
<div class="container mt-4 mb-4">
<h3>Edit Recipe</h3>

<div>
	<%= form_for @recipe do |form| %>
		<% if @recipe.errors.any? %>
			<h5>Form is invalid</h5>
			<ul>
				<% @recipe.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			</ul>
			<% end %>
		<% end %>

		<%= render partial: '/recipes/form', object: form %>
		<br>
		<div class="actions">
			<%= form.submit "Update Recipe", class:"btn btn-outline-dark" %>
			<!-- <br><br> -->
			<%= link_to "Back", recipe_path(@recipe.id), class: "btn btn-outline-secondary" %>		
		</div>
	<% end %>
</div>

app/views/recipes/index.html.erb
<div class="mt-4">
	<h1 class="mb-0"><center>Find your recipe and cook with &hearts;</h1><br></center>
	<% if logged_in? %>
		<center><%= link_to "Create new recipe", new_recipe_path, class:"mt-0 pt-0" %></center>
	<% end %>
</div>

<div class="container mt-4 mb-4">
	<% @recipes.each do |recipe| %>
	<div class="alert alert-secondary" role="alert">
	  <h4 class="alert-heading"><%= link_to recipe.title, recipe_path(recipe.id), class: "alert-link" %></h4>
	  <p><%= recipe.description %></p>
	  <hr>
	  <p class="mb-0">By <%= recipe.user.first_name + " " + recipe.user.last_name %></p>
	</div>
	<% end %>
	<div style="text-align: center;">
		<%= paginate @recipes, left: 2, right: 3%>
	</div>
</div>

app/views/recipes/new.html.erb
<div class="container mt-4 mb-4">
<h3>New Recipe</h3>

<div>
	<%= form_for @recipe do |form| %>
		<% if @recipe.errors.any? %>
			<h5>Form is invalid</h5>
			<ul>
				<% @recipe.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>

		<%= render partial: '/recipes/form', object: form %>
		<br>
		<div class="actions">
			<%= form.submit "Submit", class:"btn btn-outline-dark" %>
		</div>
	<% end %>
</div>
</div>

app/views/recipes/show.html.erb
<div class="container mt-4">
	<h3><%= @recipe.title %></h3>
	<p><%= @recipe.description.gsub("\r\n", "<br>").html_safe %></p>

	<p>
		<strong>Ingredients:</strong> <br>
		<%= @recipe.ingredients.gsub("\r\n", "<br>").html_safe %>
	</p>

	<p>
		<strong>Steps:</strong> <br>
		<%= @recipe.steps.gsub("\r\n", "<br>").html_safe %>
	</p>

	<% if @recipe.photos != [] %>
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
	    <!-- Indicators -->
	    <ol class="carousel-indicators">
	      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	      <li data-target="#myCarousel" data-slide-to="1"></li>
	      <li data-target="#myCarousel" data-slide-to="2"></li>
	    </ol>

	    <!-- Wrapper for slides -->
	    <div class="carousel-inner">
	      <div class="carousel-item active">
	        <%= image_tag @recipe.photos.first, class:"d-block w-100" %>
	      </div>
	        <% @recipe.photos.shift %>
	        <% @recipe.photos.each do |p| %>
	          <div class="carousel-item">
	            <%= image_tag p, alt: 'picture', class:"d-block w-100" %>
	          </div>
	        <% end %>
	    </div>

	    <!-- Left and right controls -->
	    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
	      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	      <span class="sr-only">Previous</span>
	    </a>
	    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
	      <span class="carousel-control-next-icon" aria-hidden="true"></span>
	      <span class="sr-only">Next</span>
	    </a>
	  </div>

	<% end %>
	<br>
	<% if logged_in? && current_user.id != @recipe.user.id %>
		<div id="poll">
			<h5>Is this recipe helpful?</h5>
			<form>
				Yes:
				<input type="radio" name="vote" value="1" onclick="getVote(this.value, <%= @recipe.id %>)">
				<br>No:
				<input type="radio" name="vote" value="0" onclick="getVote(this.value, <%= @recipe.id %>)">
			</form>
			<div id="display">
			</div>
		</div>
		<br>
	<% end %>

	Share this recipe: <%= social_share_button_tag('', :url => "http://recook.herokuapp.com/recipes/"+ @recipe.id.to_s) %>
	<br>
	<% if current_user == @recipe.user %>
		<%= link_to "Edit recipe", edit_recipe_path(@recipe) %> |
		<%= link_to "Delete", recipe_path, method: :delete, data: { confirm: 'Are you sure?'} %> |
	<% end %>
	<%= link_to "Back" ,recipes_path %> <br> <br>
	
</div>