config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'sessions#new'
  
  # Define the route to make it more friendly
  # get 'signup', to: 'users#new', as: 'signup'
  # get 'login', to: 'sessions#new', as: 'login'
  # get 'logout', to: 'sessions#destroy', as: 'logout'
  # get '/vote', to: 'votes#create', as: 'vote'


	get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # resources :users
  # resources :sessions, only: [:create]
  resources :recipes
  resources :vote, only: [:create]
  root 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_secure_password

	validates_presence_of :first_name, :last_name, :password, :email

  validates :password, length: { minimum: 7 }
  validates :email, uniqueness: true, format: { with: (/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i), message: "has registered before"}

	has_many :authentications, dependent: :destroy
	has_many :recipes, dependent: :destroy
	has_many :votes, dependent: :destroy

	# attr_accessible :avatar
	# mount_uploader :avatar, AvatarUploader

	def self.create_with_auth_and_hash(authentication, auth_hash)
    # byebug
    user = self.create!(
      first_name: auth_hash["info"]["first_name"],
      last_name: auth_hash["info"]["last_name"],
      email: auth_hash["info"]["email"],
      # photo: auth_hash["info"]["image"],
      password: SecureRandom.hex(10)
    )
    user.authentications << authentication
    return user
  end

  # grab fb_token to access Facebook for user data
  def fb_token
    x = self.authentications.find_by(provider: 'facebook')
    return x.token unless x.nil?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url, notice: "Thank you for signing up!"
		else
			render :new
		end
	end

	def index
	end

	def edit
	end

	def update
    # respond_to do |format|
      if @user.update(user_params)
      	redirect_to @user, notice: 'User was successfully updated.'
      else
        render :edit
      end
    # end
  end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end

	def set_user
  	@user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
	<div class="pt-2 pl-4 pr-4">
	<div class="field">
		<%= form.label :first_name %> <br>
		<%= form.text_field :first_name, class:"form-control" %>
	</div>
	<br>
	<div class="field">
		<%= form.label :last_name %> <br>
		<%= form.text_field :last_name, class:"form-control"  %>
	</div>
	<br>
	<div class="field">
		<%= form.label :email %> <br>
		<%= form.text_field :email, class:"form-control"  %> 
	</div>
	<br>
	<div class="field">
		<%= form.label :password %> <br>
		<%= form.password_field :password, class:"form-control"  %>
		<small id="emailHelp" class="form-text text-muted">Minimum 7 characters.</small>
	</div>
	<br>
	<div class="field">
		<%= form.label :password_confirmation %> <br>
		<%= form.password_field :password_confirmation, class:"form-control"  %>
	</div>
	<br>
</div>

	<!-- <div class="actions">
		<%#= f.submit "Sign Up" %>
	</div> -->

<%# end %>

app/views/users/edit.html.erb
<div class="container mt-4 mb-4">
<h3>Edit your profile</h3>

	<% if @user.errors.any? %>
		<h5>Form is invalid</h5>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<div>
	  <%= form_for @user do |form| %>

	  <%= render partial: '/users/form', object: form %>

	  <div class="actions">
			<%= form.submit "Update Details", class: "btn btn-outline-dark" %>
			<%= link_to "Back", user_path(current_user), class: "btn btn-outline-secondary" %>
		</div>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<div class="container mt-4 mb-4">
<h3>Sign Up</h3>

 <div>
  <%= form_for @user do |form| %>
	<% if @user.errors.any? %>
		<h5>Form is invalid</h5>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

    <%= render partial: '/users/form', object: form %>

    <div class="actions">
			<%= form.submit "Sign Up", class:"btn btn-outline-dark" %>
		</div> <br>
		<%= link_to "Sign up with Facebook", "/auth/facebook" %> |
		<%= link_to "Sign up with Google", "/auth/google_oauth2" %>
	<% end %>
	</div>


</div>

app/views/users/show.html.erb
<div class="container mt-5">
<img src="http://www.hexatar.com/gallery/thumb/151208_020651_fe104ea6634.png" alt="picture">
<br>
<br>
<div>
	<p>Name: <%= @user.first_name + " " + @user.last_name %><br>
	Member since <%= @user.created_at.strftime('%d %b %Y') %></p>
</div>

<%= link_to "Edit my profile", edit_user_path(current_user) %> |
<%= link_to "Create new recipe", new_recipe_path %> |
<%= link_to "See all recipes", recipes_path %>
</div>