config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'sessions#new'
  
  # Define the route to make it more friendly
  # get 'signup', to: 'users#new', as: 'signup'
  # get 'login', to: 'sessions#new', as: 'login'
  # get 'logout', to: 'sessions#destroy', as: 'logout'
  # get '/vote', to: 'votes#create', as: 'vote'


	get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # resources :users
  # resources :sessions, only: [:create]
  resources :recipes
  resources :vote, only: [:create]
  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recook</title>
		<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<div>
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
				<%= link_to "Recook", root_path, class: "navbar-brand" %>
  			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    			<span class="navbar-toggler-icon"></span>
  			</button>

				<% if user_signed_in? %>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
	    			<ul class="navbar-nav mr-auto">
	    				<li class="nav-item">
	    			  	<%= link_to "All recipes", recipes_path, class: "nav-link" %>
	      			</li>
	    			  <li class="nav-item">
	    			  	<%= link_to "My profile", user_path(current_user), class: "nav-link" %>
	      			</li>
	      			<li class="nav-item">
	    			  	<%= link_to "Log out", logout_path, class: "nav-link" %>
	      			</li>
	    			</ul>
	  				<div class="form-inline my-2 my-lg-0">
	    				<%= form_tag(recipes_path, class: 'form-inline', :method => "get") do %>
      				<%= text_field_tag :search, params[:search], placeholder: "Search a recipe", class:'form-control mr-sm-2'%>
     				 <%= submit_tag "Go", class:'btn btn-outline-success my-2 my-sm-0', style:'display: inline;'%>
     				 <% end %>
     				</div>
	  			</div>
				<% else %>
	  			<div class="collapse navbar-collapse" id="navbarSupportedContent">
	    			<ul class="navbar-nav mr-auto">
	    				<li class="nav-item">
	    			  	<%= link_to "All recipes", recipes_path, class: "nav-link" %>
	      			</li>
	    			  <li class="nav-item">
	    			  	<%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
	      			</li>
	      			<li class="nav-item dropdown">
	        			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          		Log In
	        			</a>
	        			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
	          			<%#= link_to "Log in with Facebook", "/auth/facebook", class: "dropdown-item" %>
	          			<%= link_to "Log in with Facebook", "/", class: "dropdown-item disabled" %>
	          			<%#= link_to "Log in with Google", "/auth/google_oauth2", class: "dropdown-item" %>
	          			<%= link_to "Log in with Google", "/", class: "dropdown-item disabled" %>
	          			<div class="dropdown-divider"></div>
	          				<%= link_to "More login option", new_user_session_path, class: "dropdown-item" %>
	        			</div>
	      			</li>
	    			</ul>
	  				<!-- <form class="form-inline my-2 my-lg-0">
	    				<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
	    				<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
						<div class="form-inline my-2 my-lg-0">
	    				<%= form_tag(recipes_path, class: 'form-inline', :method => "get") do %>
      				<%= text_field_tag :search, params[:search], placeholder: "Search a recipe", class:'form-control mr-sm-2'%>
     				 <%= submit_tag "Go", class:'btn btn-outline-success my-2 my-sm-0', style:'display: inline;'%>
     				</div>
    <% end %>
	  				<!-- </form> -->
	  			</div>
  			<% end %>
			</nav>

			<%# if logged_in? %>
				<%#= link_to "Log Out", session_path(current_user), method: :delete %>
			<%# else %>
				<%#= link_to "Sign Up", new_user_path %>
				<%#= link_to "Log In", new_session_path %>
			<%# end %>
		</div>

    <div id="flash">
    	<% flash.each do |key, value| -%>
      	<div id="flash_<%= key %>"><center><%=h value %></center></div>
    	<% end %>
    </div>

		<%= yield %>
  </body>
</html>